//subnet_id=
region      = "eu-west-0"
access_key  = ""
secret_key  = ""
domain_name = ""
# vpc_name=""
# subnet_name=""
# Listener_name=""
# ELB_name=""
certificate_name=""
# whitelist="10.3.1.0/24"
# # listener_protocol_v3="HTTPS"
# listener_port_v3=443
# # listener_protocol_v2="TERMINATED_HTTPS"
# listener_port_v2=443
# pool_protocol_v2="HTTP"
# #num_members=2
# name_regex_ecs=".*TEST-0001"
# member_port_v2=443
# member_port_v3=443
# pool_protocol_v3="HTTP"